esphome:
  name: plug
  friendly_name: Plug

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "GsYQ3Yuh5GCXlhBesjyyv4y+hoqZv9yXip5rflLz5eY="

ota:
  password: "7ca0097ba55b69dcdbbf10d2a011a87c"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Plug Fallback Hotspot"
    password: "1WtcSuFjmg2Z"

captive_portal:
    