---
substitutions:
  area: gg.cs
  device_name: boiler-power-plug
  friendly_name: Boiler Power Plug
  current_res: "0.00248"
  voltage_div: "954"

packages:
  device: !include devices/cloudfree-smart-plug.yaml
