---
# https://esphome.io/components/wifi.html

substitutions:
  domain: !secret domain

wifi:
  id: component_wifi
  ssid: !secret wifi_ssid
  use_address: "${device_name}.${area}.${domain}"
  password: !secret wifi_password
  reboot_timeout: 10min
  ap:
    ssid: "${friendly_name} AP"
    password: !secret wifi_fallback_ssid_password

captive_portal:

sensor:
  - platform: template
    id: sensor_wifi_signal_percentage
    name: "${friendly_name} WiFi Signal Percentage"
    icon: "mdi:wifi"
    unit_of_measurement: "%"
    update_interval: never
    lambda: |-
      if (id(sensor_wifi_signal).state) {
        if (id(sensor_wifi_signal).state <= -100 ) {
          return 0;
        } else if (id(sensor_wifi_signal).state >= -50) {
          return 100;
        } else {
          return 2 * (id(sensor_wifi_signal).state + 100);
        }
      } else {
        return NAN;
      }
  - platform: wifi_signal
    id: sensor_wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 300s
    on_value:
      - component.update: sensor_wifi_signal_percentage

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
    ssid:
      name: "${friendly_name} Connected SSID"
    bssid:
      name: "${friendly_name} Connected BSSID"
    mac_address:
      name: "${friendly_name} Connected MAC"
